title: Ride The Reef
description: "This website is where I will be posting Blogs written about Typography "
header_text: Reef Riders
footer_text: Copyright 2020 Poppy Clark
header_feature_image: ../uploads/surfing.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
